title: Hunter's Personal Website
email: terminalconnectionhunter@gmail.com
url: "terminalhunter.github.io" # the base hostname & protocol for your site
twitter_username: terminalhunter
github_username:  terminalhunter

markdown: kramdown
theme: minima